name: auto changelog

on:
  push:
    tags:
      - 'v*'

jobs:
  changelog:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: npx changelogithub
        env:
          GITHUB_TOKEN: ${{secrets.GH_PAT}}
